name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        # --ignore-scripts is put to avoid capacitor sync during install on CI
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        # --ignore-scripts is put to avoid capacitor sync during install on CI
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build
        run: pnpm build
